### ISSUE TITLE
Missing log configuration

### ISSUE THREAD

**Issue by chouseknecht** [ansible/mazer#114]
##### GALAXY CLI VERSION
```
name = mazer
version = 0.2.0
config_file = /Users/chouseknecht/.ansible/mazer.yml
uname = Darwin, cyclone.local, 17.7.0, Darwin Kernel Version 17.7.0: Thu Jun 21 22:53:14 PDT 2018; root:xnu-4570.71.2~1/RELEASE_X86_64, x86_64
executable_location = /Users/chouseknecht/.pyenv/versions/venv27/bin/mazer
python_version = 2.7.14 (default, Nov 14 2017, 23:24:24) [GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.38)]
python_executable = /Users/chouseknecht/.pyenv/versions/2.7.14/envs/venv27/bin/python2.7
```

##### CONFIGURATION
```
version: 1
server:
  url: https://galaxy-qa.ansible.com
  ignore_certs: False

content_path: ~/.ansible/content
```
##### SUMMARY
Running the command `mazer install --namespace forklift git+https://github.com/theforeman/forklift`, and expecting the log file, `~/.ansible/mazer.log` to be created, but no joy.

##### STEPS TO REPRODUCE
1. Install Mazer using `pip install --upgrade mazer` or `pip install -v git+ssh://git@github.com/ansible/mazer.git`
2. Run the command `mazer install --namespace forklift git+https://github.com/theforeman/forklift` to install some content
3. See that there is no `~/.ansible/mazer.log`
4. Notice also, an error has occurred, and not all of the expected roles were installed, yet no error was thrown on the command line.

##### EXPECTED RESULTS

If an error occurs, I expect to see in stdout/stderr some indication of what went wrong. I also expect to see a log file in `~/.ansible/mazer.log`.

**Comment by tabulon** [comment]
Hi,
How do we set the directory where mazer logs are written? 
(in a way similar to "log_path" in ansible.cfg)

Currently the mazer log filles (e.g. "mazer.log", "mazer-http.log") are created/written right next to where the mazer configuration file (mazer.yml) resides.

I am just hoping that this is just a default location (a poor choice,  imho) which can be modified through some configuration.

There is a vague mention of "mazor-logging.yml" in the docs, but without any explanation of its expected contents.
