### ISSUE TITLE
Add Molecule support to `init`

### ISSUE THREAD

**Issue by chouseknecht** [ansible/mazer#140]
The default project structure created by `init` will include a `molecule` directory at the root of the project.

For each role added to the project by `mazer init role foo`, the new role structure will include a `molecule` directory at the root. 

Within a `molecule` directory, Mazer will add a default scenario, and any supporting files needed by Molecule. After the `init` command completes, it should be possible to run `molecule` to successfully test the project.

**Comment by chouseknecht** [comment]
We've decided to nuke the `init` command from Mazer, and focus on using Molecule as the developer workflow tool. `init` will become part of Mazer.

**Comment by decentral1se** [comment]
:+1:
