### ISSUE TITLE
Role Metadata

### ISSUE THREAD

**Issue by chouseknecht** [ansible/mazer#21]
- [ ] Add a *version* to `meta/main.yml`. Propose we set the first version to '2.0'. 
- [ ] Remove the *github_branch* element from version 2. Think this is no longer needed, if we begin enforcing version tags on repositories. The import process should only import new, tagged versions.
- [ ] Add *cloud_platforms* to 2.0
- [x] Add *role_name* -an alternate name for the role, if the repo name should not be used.

**Comment by alikins** [comment]
@chouseknecht what are some example valid values for cloud_platforms?
