### ISSUE TITLE
Content Namespacing

### ISSUE THREAD

**Issue by chouseknecht** [ansible/mazer#25]
It seems possible that content may come from different sources or namespaces, and end up being installed with the same name. We need to enumerate how to detect a name collision for each content type, and decide how to resolve or surface an error.

**Comment by alikins** [comment]
This is fixed in devel (as of before at least 130e2db27c2253dad70ac26b4b82cd7edbb69dbd)
by the ~/.ansible/content/namespace.reponame/ style install.
