### ISSUE TITLE
Roles are not properly namepsaced on install

### ISSUE THREAD

**Issue by chouseknecht** [ansible/mazer#31]
##### GALAXY CLI VERSION
NA

##### CONFIGURATION
NA

##### SUMMARY
Installing roles from a multi-content repository should install roles as `<namespace>.<role-name>`; however, the `<namespace>` is not being included.

##### STEPS TO REPRODUCE
Install all roles: 
```bash
ansible-galaxy-cli content-install -t role atestuseraccount.ansible-testing-content
```

Or, install a single role:
```bash
ansible-galaxy-cli content-install -t role atestuseraccount.ansible-testing-content.ansible-role-foobar
```
 
##### EXPECTED RESULTS
When installing all roles, the installed directory tree should look like the following:
```
~/.ansible/content/roles
    atestuseraccount.ansible-role-foobar
    atestuseraccount.ansible-test-role-1
    atestuseraccount.test-role-a
    ...
```

When installing a single role, `ansible-role-foolbar`, the directory tree should look like the following:

```
~/.ansible/content/roles
    atestuseraccount.ansible-role-foobar
```

##### ACTUAL RESULTS
Roles are installed without the `atestuseraccount` namespace.

**Comment by alikins** [comment]
From face-to-face meeting discussions:

Possible namespace approach:

~/.ansible/content/<namespace>/
~/.ansible/content/<namespace>/roles/

For ex:

~/.ansible/content/debops/roles/apache/
~/.ansible/content/geerlingguy/roles/ntp/
~/.ansible/content/geerlingguy/roles/apache

This will require some ansible/ansible changes to understand it needs to translate playbook with "roles: [geerlingguy.apache]"  to knowing to load the role from ~/.ansible/content/geerlingguy/roles/apache


- For cases without an explicit namespace (ie, cli installs from a git repo or tarball) require a namespace provided or error. ie, ( --namespace )

- multi content repos will not use a namespace in the role name in the repo or archive

In the archive for github.com/my-github-org/my-multi-repo my-multi-repo-1.0.0.tar.gz:

```
     my-multi-repo-1.0.0/
                           roles/
                                   my-content-name/
                                   some-other-role/
                                   setup_epel/
```

This is in contrast to using namespace and reponame for the role name or namespace and content name. ie
    - NOT 'content/roles/my-multi-repo.my-content-name/meta/main.yml'
    - NOT 'content/roles/my-namespace.my-multi-repo.my-content-name/meta/main.yml'
    - NOT 'content/my-namespace.my-content-name/roles/meta/'


mazer install testing.ansible-test-content will install to:
(note 'ansible-test-content' is the repo name here)

~/.ansible/content/
~/.ansible/content/testing.ansible-test-content/
~/.ansible/content/testing.ansible-test-content/roles/
~/.ansible/content/testing.ansible-test-content/roles/test-role-a/
   (  ~/.ansible/content/testing.ansible-test-content/roles/test-role-a/meta/main.yml etc)
~/.ansible/content/testing.ansible-test-content/roles/test-role-b/
  (etc)

**Comment by alikins** [comment]
3ab494db63e694b5d116ac97eef37b4b7a5e8035 and 604f5aea69eccbe3d0a4b409f8277f07fbd46272 fixes this.

At least for the scheme described in https://github.com/ansible/mazer/issues/31#issuecomment-396597450
