### ISSUE TITLE
As a user, I expect 'remove' to delete previously installed content

### ISSUE THREAD

**Issue by chouseknecht** [ansible/mazer#41]
- [x] `ansible-galaxy remove <namespace>.<repository>` removes requested content from the local filesystem
- [x] `ansible-galaxy remove <namespace>.<repository>` fails gracefully, if requested content not found
- [x] For this iteration, ignore dependencies
- [x] Add unit test coverage

**Comment by alikins** [comment]
Fixed in 205955a4ca8f10a603fa9d198bd313230c8da7e2
