### ISSUE TITLE
As a user, I expect 'list' to show what's currently installed

### ISSUE THREAD

**Issue by chouseknecht** [ansible/mazer#42]
- [x] `ansible-galaxy list` should show a list of installed roles in the format: 

    ```
    <namespace>.<repository_name> version
    <namespace>.<repository_name> version
    <namespace>.<repository_name> version
    ....
    ```
- [x] Until we know how to namespace modules and plugins, hold off on listing installed modules and plugins. 
- [x] Add unit test coverage

**Comment by alikins** [comment]
Fixed by eb88fd1215ef1749b20167482f91b7a875461eb9

example list output atm
```
repo=geerlingguy.nginx, type=role, name=nginx, version=2.5.0
repo=GROG.debug, type=role, name=debug, version=1.2.3
repo=geerlingguy.apache, type=role, name=apache, version=2.1.1
```
