### ISSUE TITLE
As a user, I expect to install the CLI from PyPi

### ISSUE THREAD

**Issue by chouseknecht** [ansible/mazer#45]
- [x] package and push to TestPyPi and sort out any issues
- [x] package and push to PyPi
- [x] automate the process of pushing a release to PyPi via Ansible playbook and Jenkins
- [x] document the release process
- [x] push the first release

**Comment by alikins** [comment]
Added travis support as well as a pre-req of this. https://travis-ci.org/ansible/mazer

**Comment by alikins** [comment]
https://github.com/ansible/mazer/pull/83  related pr

**Comment by chouseknecht** [comment]
Mazer is now on PyPi: https://pypi.org/project/mazer/
