### ISSUE TITLE
As a user, I should only see commands that actually work

### ISSUE THREAD

**Issue by chouseknecht** [ansible/mazer#46]
- [ ] disable commands not in: install, remove, list, init, version
- [ ] verify `ansible-galaxy-cli --help` does not include commands outside of the above list
- [ ] verify that when given a command not in the above list, the CLI fails gracefully

**Comment by alikins** [comment]
To be removed commands:

- [x] import
- [x] login
- [x] delete
- [x] search
- [x] setup
- [x] content-install  (exists as alias only in dev version)
