### ISSUE TITLE
Limit scope of installable content

### ISSUE THREAD

**Issue by chouseknecht** [ansible/mazer#49]
There's still a lot of questions around modules and plugins, mainly the following:

- How to prevent certain things being included in module_utils (i.e., basic.py)
- How to handle name collisions
- How to collect more metadata
- How to handle dependencies

For this reason, we will limit for the v3.0 release of the client (not sure what version we're actually calling it, but the version we release at the end of June) what can be installed to the following: 

- Traditional roles
- all roles from a multi-content repository
- a single role from a multi-content repository

Support for modules and plugins will be included in the next release, assuming we have answers to the above questions.

**Comment by alikins** [comment]
Fixed in devel at sometime before 91262d9876c3d486c816b057f54a6a44affd19e1
