### ISSUE TITLE
Reliable content version compares and sorts

### ISSUE THREAD

**Issue by chouseknecht** [ansible/mazer#56]
There are lots of situations where the CLI does or will perform version comparison. We have a similar situation on the server side as well. In both cases we need to reliably sort versions, or compare two versions, and make decisions. 

To close this issue, we need the following: 

- [x] choose an existing library, or build a solution that uses the semantic version spec to sort and compare versions
- [x] coordinate with the Galaxy Server team, and copy or use the same tools/code to perform version compares and sorts. Comparison and sort operations should yield the same results from both server and client

**Comment by alikins** [comment]
See https://github.com/ansible/mazer/pull/87

**Comment by alikins** [comment]
Closed with https://github.com/ansible/mazer/commit/cc137ad474812e9ca80cca690969cbb7dab88bc0 when https://github.com/ansible/mazer/pull/87 was merged.
