### ISSUE TITLE
Deprecate 'role_name' from metadata

### ISSUE THREAD

**Issue by alikins** [ansible/mazer#62]
This is the client side of  https://github.com/ansible/galaxy/pull/577

**Comment by chouseknecht** [comment]
@tima

When should *role_name* be used by the `install` command? For example, should it be used when installing from a git URL, as suggested by [galaxy #939](ttps://github.com/ansible/galaxy/issues/939)?

**Comment by chouseknecht** [comment]
@alikins 

We decided in the Galaxy CLI Developer Workflow meetings that we want to deprecate the use of `role_name` in metadata.

For reference see https://docs.google.com/document/d/1nx65quXCyYORNel72rRCovyQo_qO5fhHlqrnKyYNlYU/edit?usp=sharing

I *think* it would be helpful to issue a deprecation warning `role_name` is found in `meta/main.yml`. We need to start letting people know that Galaxy is getting out of the business of overriding repository names.

**Comment by alikins** [comment]
Closing WONTFIX in lieu of moving away from support of installing traditional roles directly.
