### ISSUE TITLE
README outdated

### ISSUE THREAD

**Issue by chouseknecht** [ansible/mazer#75]
Since our original README, a few things have changed, and an update is needed:

- [x] We're only allowing install of full repositories. It should no longer be possible, and certainly not documented, that one can install individual pieces of content from a multi-content repo. 
- [x] We've introduced `~/.ansible/mazer.yml` as the config file. Need to provide an example, explain what options are available, how to use, etc.
- [x] Our directory structure for installed content has changed as well, I believe

**Comment by alikins** [comment]
Fixed by https://github.com/ansible/mazer/issues/75
